Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Enabled: true
  Max: 100
Metrics/BlockLength:
  CountComments: false
  Max: 25
  ExcludedMethods: ['describe', 'context', 'it']
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 15
  Exclude:
  - "spec/**/*"  